package com.dao;

import com.entity.UserDemo;
import com.entity.UserDemoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbg.generated
     */
    long countByExample(UserDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbg.generated
     */
    int deleteByExample(UserDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbg.generated
     */
    int insert(UserDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbg.generated
     */
    int insertSelective(UserDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbg.generated
     */
    List<UserDemo> selectByExample(UserDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbg.generated
     */
    UserDemo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserDemo record, @Param("example") UserDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserDemo record, @Param("example") UserDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_demo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDemo record);
}